// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, user_id, token_hash, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, token_hash, created_at, last_used_at
`

type CreateAPITokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUserWithCredentials = `-- name: CreateUserWithCredentials :one
INSERT INTO users (id, created_at, updated_at, name, email, password_hash)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, email, password_hash
`

type CreateUserWithCredentialsParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	Email        sql.NullString
	PasswordHash string
}

func (q *Queries) CreateUserWithCredentials(ctx context.Context, arg CreateUserWithCredentialsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithCredentials,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, name, email, password_hash FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByTokenHash = `-- name: GetUserByTokenHash :one
SELECT users.id, users.created_at, users.updated_at, users.name, users.email, users.password_hash FROM users
JOIN api_tokens ON api_tokens.user_id = users.id
WHERE api_tokens.token_hash = $1
`

func (q *Queries) GetUserByTokenHash(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTokenHash, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
