// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, last_error, failure_count
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.Etag,
		&i.LastModified,
		&i.LastError,
		&i.FailureCount,
	)
	return i, err
}

const getBrokenFeeds = `-- name: GetBrokenFeeds :many
SELECT id, name, url, last_error, failure_count, last_fetched_at
FROM feeds
WHERE failure_count > 0
ORDER BY failure_count DESC, name
`

type GetBrokenFeedsRow struct {
	ID            uuid.UUID
	Name          string
	Url           string
	LastError     string
	FailureCount  int32
	LastFetchedAt sql.NullTime
}

func (q *Queries) GetBrokenFeeds(ctx context.Context) ([]GetBrokenFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBrokenFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBrokenFeedsRow
	for rows.Next() {
		var i GetBrokenFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.LastError,
			&i.FailureCount,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByUrl = `-- name: GetFeedByUrl :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, last_error, failure_count FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.Etag,
		&i.LastModified,
		&i.LastError,
		&i.FailureCount,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT feeds.name, feeds.url, users.name AS user_name,
       feeds.last_error, feeds.failure_count
FROM feeds
JOIN users ON feeds.user_id = users.id
`

type GetFeedsRow struct {
	Name         string
	Url          string
	UserName     string
	LastError    string
	FailureCount int32
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.UserName,
			&i.LastError,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsToFetch = `-- name: GetFeedsToFetch :many
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, last_error, failure_count FROM feeds
ORDER BY last_fetched_at ASC NULLS FIRST
`

func (q *Queries) GetFeedsToFetch(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsToFetch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
			&i.Etag,
			&i.LastModified,
			&i.LastError,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, last_error, failure_count FROM feeds
ORDER BY last_fetched_at ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.Etag,
		&i.LastModified,
		&i.LastError,
		&i.FailureCount,
	)
	return i, err
}

const markFeedFailed = `-- name: MarkFeedFailed :exec
UPDATE feeds
SET last_error = $2, failure_count = failure_count + 1, updated_at = NOW()
WHERE id = $1
`

type MarkFeedFailedParams struct {
	ID        uuid.UUID
	LastError string
}

// failure_count raste po uzastopnim neuspesima; resetuje ga tek uspeh.
func (q *Queries) MarkFeedFailed(ctx context.Context, arg MarkFeedFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFailed, arg.ID, arg.LastError)
	return err
}

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET last_fetched_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, id)
	return err
}

const markFeedHealthy = `-- name: MarkFeedHealthy :exec
UPDATE feeds
SET last_error = '', failure_count = 0, updated_at = NOW()
WHERE id = $1 AND (last_error <> '' OR failure_count <> 0)
`

// Uslov na kraju stedi upis kod feedova koji su i inace zdravi, sto je vecina
// u svakom krugu.
func (q *Queries) MarkFeedHealthy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFeedHealthy, id)
	return err
}

const saveFeedValidators = `-- name: SaveFeedValidators :exec
UPDATE feeds
SET etag = $2, last_modified = $3, updated_at = NOW()
WHERE id = $1
`

type SaveFeedValidatorsParams struct {
	ID           uuid.UUID
	Etag         string
	LastModified string
}

// Odvojeno od MarkFeedFetched, koji se namerno izvrsava pre preuzimanja da feed
// koji stalno puca ne bi bio pokusavan u svakom krugu. Validatori se, naprotiv,
// znaju tek posle uspesnog odgovora.
func (q *Queries) SaveFeedValidators(ctx context.Context, arg SaveFeedValidatorsParams) error {
	_, err := q.db.ExecContext(ctx, saveFeedValidators, arg.ID, arg.Etag, arg.LastModified)
	return err
}

const setFeedUrl = `-- name: SetFeedUrl :exec
UPDATE feeds
SET url = $2, updated_at = NOW()
WHERE id = $1
`

type SetFeedUrlParams struct {
	ID  uuid.UUID
	Url string
}

func (q *Queries) SetFeedUrl(ctx context.Context, arg SetFeedUrlParams) error {
	_, err := q.db.ExecContext(ctx, setFeedUrl, arg.ID, arg.Url)
	return err
}
