// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_reads.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getReadPostIDs = `-- name: GetReadPostIDs :many
SELECT post_id FROM post_reads
WHERE user_id = $1
`

func (q *Queries) GetReadPostIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getReadPostIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var post_id uuid.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCountsForUser = `-- name: GetUnreadCountsForUser :many
SELECT posts.feed_id, count(*) AS unread
FROM posts
JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
LEFT JOIN post_reads
    ON post_reads.post_id = posts.id
   AND post_reads.user_id = feed_follows.user_id
WHERE feed_follows.user_id = $1
  AND post_reads.post_id IS NULL
GROUP BY posts.feed_id
`

type GetUnreadCountsForUserRow struct {
	FeedID uuid.UUID
	Unread int64
}

func (q *Queries) GetUnreadCountsForUser(ctx context.Context, userID uuid.UUID) ([]GetUnreadCountsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadCountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadCountsForUserRow
	for rows.Next() {
		var i GetUnreadCountsForUserRow
		if err := rows.Scan(&i.FeedID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostRead = `-- name: MarkPostRead :exec
INSERT INTO post_reads (user_id, post_id, read_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, post_id) DO NOTHING
`

type MarkPostReadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
	ReadAt time.Time
}

func (q *Queries) MarkPostRead(ctx context.Context, arg MarkPostReadParams) error {
	_, err := q.db.ExecContext(ctx, markPostRead, arg.UserID, arg.PostID, arg.ReadAt)
	return err
}

const markPostUnread = `-- name: MarkPostUnread :exec
DELETE FROM post_reads
WHERE user_id = $1 AND post_id = $2
`

type MarkPostUnreadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) MarkPostUnread(ctx context.Context, arg MarkPostUnreadParams) error {
	_, err := q.db.ExecContext(ctx, markPostUnread, arg.UserID, arg.PostID)
	return err
}

const markPostsRead = `-- name: MarkPostsRead :exec
INSERT INTO post_reads (user_id, post_id, read_at)
SELECT $1, unnest($2::uuid[]), $3
ON CONFLICT (user_id, post_id) DO NOTHING
`

type MarkPostsReadParams struct {
	UserID  uuid.UUID
	PostIds []uuid.UUID
	ReadAt  time.Time
}

func (q *Queries) MarkPostsRead(ctx context.Context, arg MarkPostsReadParams) error {
	_, err := q.db.ExecContext(ctx, markPostsRead, arg.UserID, pq.Array(arg.PostIds), arg.ReadAt)
	return err
}
