// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const countAllRows = `-- name: CountAllRows :one
SELECT
    (SELECT count(*) FROM users)        AS users,
    (SELECT count(*) FROM feeds)        AS feeds,
    (SELECT count(*) FROM posts)        AS posts,
    (SELECT count(*) FROM feed_follows) AS feed_follows,
    (SELECT count(*) FROM bookmarks)    AS bookmarks,
    (SELECT count(*) FROM post_reads)   AS post_reads,
    (SELECT count(*) FROM api_tokens)   AS api_tokens
`

type CountAllRowsRow struct {
	Users       int64
	Feeds       int64
	Posts       int64
	FeedFollows int64
	Bookmarks   int64
	PostReads   int64
	ApiTokens   int64
}

func (q *Queries) CountAllRows(ctx context.Context) (CountAllRowsRow, error) {
	row := q.db.QueryRowContext(ctx, countAllRows)
	var i CountAllRowsRow
	err := row.Scan(
		&i.Users,
		&i.Feeds,
		&i.Posts,
		&i.FeedFollows,
		&i.Bookmarks,
		&i.PostReads,
		&i.ApiTokens,
	)
	return i, err
}

const truncateAll = `-- name: TruncateAll :exec
TRUNCATE users, feeds, posts, feed_follows, bookmarks, post_reads, api_tokens
`

func (q *Queries) TruncateAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateAll)
	return err
}
