// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFeedStatsForUser = `-- name: GetFeedStatsForUser :many
SELECT
    feeds.id AS feed_id,
    feeds.name AS feed_name,
    feeds.url AS feed_url,
    feed_follows.category,
    feeds.failure_count,
    COUNT(posts.id) AS post_count,
    COUNT(posts.id) FILTER (WHERE posts.published_at >= $1::timestamp) AS recent_count,
    COUNT(post_reads.post_id) AS read_count,
    COUNT(bookmarks.post_id) AS bookmark_count,
    COALESCE(MAX(posts.published_at), '0001-01-01 00:00:00'::timestamp)::timestamp AS last_published,
    COALESCE(MAX(post_reads.read_at), '0001-01-01 00:00:00'::timestamp)::timestamp AS last_read
FROM feed_follows
JOIN feeds ON feeds.id = feed_follows.feed_id
LEFT JOIN posts ON posts.feed_id = feeds.id
LEFT JOIN post_reads
    ON post_reads.post_id = posts.id
   AND post_reads.user_id = feed_follows.user_id
LEFT JOIN bookmarks
    ON bookmarks.post_id = posts.id
   AND bookmarks.user_id = feed_follows.user_id
WHERE feed_follows.user_id = $2
GROUP BY feeds.id, feeds.name, feeds.url, feed_follows.category, feeds.failure_count
ORDER BY post_count DESC, feeds.name ASC
`

type GetFeedStatsForUserParams struct {
	Since  time.Time
	UserID uuid.UUID
}

type GetFeedStatsForUserRow struct {
	FeedID        uuid.UUID
	FeedName      string
	FeedUrl       string
	Category      string
	FailureCount  int32
	PostCount     int64
	RecentCount   int64
	ReadCount     int64
	BookmarkCount int64
	LastPublished time.Time
	LastRead      time.Time
}

// Jedan red po feedu koji korisnik prati, sa svime sto treba da se proceni
// vredi li ga i dalje pratiti: koliko objavljuje, koliko si od toga otvorio i
// kad je poslednji put dao znak zivota.
//
// Feed bez ijednog posta nema MAX, pa se prazan rezultat svodi na nulto vreme
// umesto na NULL — isti dogovor koji GetPostsForUserFiltered koristi za @since.
func (q *Queries) GetFeedStatsForUser(ctx context.Context, arg GetFeedStatsForUserParams) ([]GetFeedStatsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedStatsForUser, arg.Since, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedStatsForUserRow
	for rows.Next() {
		var i GetFeedStatsForUserRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedName,
			&i.FeedUrl,
			&i.Category,
			&i.FailureCount,
			&i.PostCount,
			&i.RecentCount,
			&i.ReadCount,
			&i.BookmarkCount,
			&i.LastPublished,
			&i.LastRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
